### ISSUE TITLE
"Unknown ID" on unjoined jams upon refresh

### ISSUE THREAD

**Issue by jgusta** [Unbundlesss/OUROVEON#5]
When I leave a jam in Endlesss, but have downloaded the jam in LORE, the name of the jam becomes "[ Unknown ID ]" when refreshing LORE on the login screen. 

In other words, I must be currently subscribed to a jam in order to have the name show up properly.

On the one hand, this makes total sense; LORE aims to keep up to date with the jam and grabs the latest information when you tell it to refresh everything. However; as an archiving tool, this is problematic.

For example, I've downloaded some old solo jams that I still had "joined". Wanting to remove these from my ever-growing jam list (thus speeding up Endlesss load times), I then unjoined these jams.  Being the last (and only) person in the jam, leaving means permanent deletion of the jam.

LORE faithfully holds and replays these deleted entries, but refreshing changes the name to "[ Unknown ID ]" and I'll need to get the original names back some other way. Luckily I found this by testing it out first, but others may not be so lucky.

I would propose that jams that are no longer valid be frozen with the latest name known. Maybe flagged as an archive or something like that, so they are not refetched.

It's a pesky thing to ask about but I wanted to bring it to attention because it seems important.

**Comment by ishani** [comment]
Yes, that's a fair complaint. We do have the archive of public/join-in jams and I think perhaps it just needs to expand to include any ever seen - or potentially having a way to specify names manually in the case where the jam no longer exists. 

I'll have a think how best to keep these intact / bring them back.

**Comment by ishani** [comment]
I've been looking at this bug while doing some refactoring; turns out, the data is not lost (or shouldn't be), there is just a bug where the UI code isn't using all the data sources available to it when looking up Jam names.

Whenever you run LORE, it takes your current cache of jams - ones you've joined, publics, all of it - and stashes the ID/name into the Warehouse database. So if you've *ever* seen a jam, it should at least have a named record of it.

All that was missing was to properly check that 'historical record' when resolving names. Latest version will fix this! 

(I'm also looking at adding the ability to set custom name overrides and tags too)
